# Generated by Django 4.1.3 on 2022-11-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_', '0003_comment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
