# Generated by Django 4.1.3 on 2022-11-15 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_', '0006_likedpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedPost',
            new_name='Like',
        ),
    ]
