# Generated by Django 4.1.3 on 2022-11-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_', '0007_rename_likedpost_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
