# Generated by Django 4.1.3 on 2022-11-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_', '0010_photoofuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoOfUser',
        ),
    ]
